apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: iqluyuwjv-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e2a7919027.1wmc.p3.openshiftapps.com/rhtap/rhtap-qe:aedcbe5c776b9d874744b546ce7cb012a6bda8bf@sha256:ec2d8273d270e56719432b1dd9a1cf75a6955a85dea9220def12f0c4ba63c5e2
        name: container-image  
